---
abstract: 'C++ version of Algorithm::ConstructDFA'
author:
  - 'Bjoern Hoehrmann <bjoern@hoehrmann.de>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-ConstructDFA-XS
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::ConstructDFA: 0
  Config: 0
  Data::AutoBimap: 0
  Graph::Directed: 0
  Graph::RandomPath: 0
  List::MoreUtils: 0
  List::UtilsBy: 0
  Memoize: 0
  Storable: 0
  Test::More: 0
  perl: 5.012
resources:
  repository: https://github.com/hoehrmann/Algorithm-ConstructDFA-XS.git
version: 0.09
